# Random Modules

1. Random number does not mean a different number everytime
2. Random means something that can not be logically predicted

### Pseudo Random and True Random

1. Computers works on Programs, and Programs are definative set of instruction.
2. So that means there must be some algorithm to generate random number as well.
3. If there is a program to generate random number it can be predicted, so it is called as True Random.
4. Random Numbers generated through algorithm are called as Pseudo Random
5. we do not need truly random numbers, unless its related to security [Example. Encryption Kyes] or
6. Basis of application is the randomness [Example. Digital roulette wheels]

In [20]:
from numpy import random

### Generate random integer number

In [47]:
x =  random.randint(10,20)
print(x)

18


### Generate random Float number

In [45]:
# return random numbers betweeen 0 and 1
x =  random.rand()
print(x)

0.7669093653260308


In [46]:
x =  random.rand(5)
print(x)

[0.73598253 0.65846831 0.11746977 0.99260747 0.48166294]


## Generate Random Array:
    1. 1-D Array
    2. 2-D Array
    3. 3-D Array
 

### 1. Integer:
    1. randint method takes size parameter where you can specify the shape of Array

In [24]:
x = random.randint(100, size =(10))
print(x)

[11 33 24 70 94 40 69 23  7 12]


In [25]:
x = random.randint(10, size =(7))
print(x)

[3 5 0 8 3 3 6]


In [26]:
x = random.randint(100, size =(3,5))
print(x)

[[58 49 13 38 86]
 [65 96 91 73 54]
 [79 88 78 27 40]]


In [27]:
x = random.randint(100, size =(3,2,5))
print(x)

[[[42 32 14 23 85]
  [87  1 78 47 52]]

 [[13 66 37 55 51]
  [41 22 46 70 26]]

 [[80 96 87  0 85]
  [92 63 98 86 36]]]


In [28]:
x = random.rand(100, size =(3,2,5))
print(x)

TypeError: rand() got an unexpected keyword argument 'size'

### 2. Float:
    1. The Rand() method also allows to specify the shape of array

In [32]:
x =  random.rand(5)
print(x)

[0.49227108 0.50272104 0.53060342 0.5105183  0.81878174]


In [33]:
x =  random.rand(3,5)
print(x)

[[0.50690597 0.7416963  0.12991227 0.44749118 0.32685178]
 [0.76173089 0.83264515 0.93295781 0.4444281  0.55505648]
 [0.94706081 0.24855957 0.7817458  0.89691178 0.2547335 ]]


In [34]:
x =  random.rand(3,2,5)
print(x)

[[[0.94924041 0.54158627 0.20957085 0.30280676 0.60643197]
  [0.37276036 0.46552061 0.02506762 0.1253871  0.82757042]]

 [[0.7653483  0.41946642 0.73120199 0.67880788 0.2618757 ]
  [0.94669174 0.03420021 0.6834183  0.23650665 0.85248192]]

 [[0.78650899 0.99006189 0.67690871 0.64775979 0.91551666]
  [0.83665027 0.85628082 0.42576557 0.83199938 0.15036674]]]


## Generate Random Numbers from Array

1. choice() method allows you to generate random numbers based on array of Value
2. choice() method takes an array as parameter and randomly returns one of the Values
3. Choice() method allows you to reutrn array of values
4. choice() method takes size as parameter to specify the shape of array

In [35]:
x = random.choice([20,43,39,88,7,84,49,47,42])
print(x)

43


In [36]:
x = random.choice([20,43,39,88,7,84,49,47,42], size = (2,3))
print(x)

[[47  7 42]
 [42 84 20]]


In [37]:
x = random.choice([20,43,39,88,7,84,49,47,42], size = (3,5))
print(x)

[[88 43 49 43 39]
 [20  7 20  7 43]
 [20 49 39 42 42]]


In [38]:
x = random.choice([20,43,39,88,7,84,49,47,42], size = (3,2,5))
print(x)

[[[42 43 39 43 20]
  [42 42 43 42 42]]

 [[20 88 88 20 39]
  [47 47 39 84  7]]

 [[ 7 43 43 84 84]
  [20 49 88 84 39]]]


# Data Distribution

### 1. What is Data Distribution?

1. Data distribution is list of all possible values, and how often each value occurs
2. List are important when working with statistics and Data Science
3. Random module allows you to return randomly generated data distribution

### Random Distribution

1. Random distribution is set of random number that follows certain probability density function
2. **probability density function** A function that describes contineous Probability i.e. Probability of all values in an array
3. We can generate random numbers based on defined probabiliy choice() method of the random module
4. choice() method allows us to specify the probability for each value
5. Probability is set of by a number between 0 and 1, 
6. where 0 means that the will never occors and 1 means that the value will always occurs

### Example

1. Generate 1-D array containing 100 values, where each value has to be 3,5,7,9:
    1. The Probability for value [3] is set to be [0.1]
    2. The Probability for value [5] is set to be [0.3]
    3. The Probability for value [7] is set to be [0.6]
    4. The Probability for value [9] is set to be [0.0]

In [39]:
from numpy import random

x = random.choice([3,5,7,9], p =[0.1,0.3,0.6,0.0], size = (2,3))
print(x)

[[7 7 7]
 [7 7 3]]


**Note : The sum of all Probability should be 1** 

### There are Different Data Distrubution types:
    1. Random Permutation
    2. Seaborn Module
    3. Normal Distribution (imp)
    4. Binomial Distribution (imp)
    5. Poission Distribution (imp)
    6. Uniform Distribution
    7. Logistic Distribution (imp)
    8. Multinomial Distribution (imp)
    9. Exmponential Distribution
    10. Chi Square Distribution (imp)
    11. Rayleigh Distribution
    12. Pareto Distribution
    13. Zipf Distribution 

In [40]:
from numpy import random

height = random.normal(2,3, size=(3,4))

print(height)

[[ 5.44642279  1.11655734  0.04675091  1.57830111]
 [-4.11728335  4.0959244   0.10136466  1.03967162]
 [ 4.04894937  0.81437971  0.72980987  4.29925275]]


In [41]:
# help(random.normal)