# Numpy

In [1]:
import numpy as np

In [5]:
my_array = np.array([10,20,30,40,50,60,70])

x = np.searchsorted(my_array, 30, side='left')
print(x)

2


In [6]:
my_array = np.array([10,20,30,40,50,60,70])

x = np.searchsorted(my_array, [40,50,60])
print(x)

[3 4 5]


# Sorting Arrays

1. Sorting means putting elements in ordered sequence
2. Ordered sequence is any sequence that has order corresponding elements
3. Like numeric or alphabetical,ascending or descending
4. Numpy having function called [sort()] that will sort in specified array

In [7]:
import numpy as np

my_array = np.array([2,87,42,5,8,23,46,41,100,50,20,34])

x = np.sort(my_array)
print(x)

[  2   5   8  20  23  34  41  42  46  50  87 100]


In [9]:
import numpy as np

my_array = np.array([2,87,42,5,8,23,46,41,100,50,20,34])

print(np.sort(my_array))
print(my_array)

[  2   5   8  20  23  34  41  42  46  50  87 100]
[  2  87  42   5   8  23  46  41 100  50  20  34]


In [10]:
my_fruits = np.array(['banana','apple','cherry','watermelon','pineapple', 'blackcurrent','papaya'])

sorted_fruits_list = np.sort(my_fruits)
print(sorted_fruits_list)

['apple' 'banana' 'blackcurrent' 'cherry' 'papaya' 'pineapple'
 'watermelon']


In [13]:
# help(np.sort(my_array))

In [15]:
my_array = np.array([True, False, True, True, True, False])

x = np.sort(my_array)
print(x)

[False False  True  True  True  True]


## Sorting a 2-D Array

In [17]:
my_array = np.array([[80,4,6,42],[12,81,24,46]])

x = np.sort(my_array)
print(x)

[[ 4  6 42 80]
 [12 24 46 81]]


# Filter Array

1. Getting some elements out of an existing array and Creating new array out of them is called Filtering
2. Filter array using boolean index list
3. Boolean index list is list of Boolean corrsponding to indexes in the array

In [2]:
import numpy as np

In [4]:
my_array = np.array([41,42,43,44])

x = [True, False, True, False]

new_array = my_array[x]
print(new_array)

[41 43]


In [21]:
my_array = np.array([41,42,43,44,78,45])

x = [True, False, True, False, True, True]

new_array = my_array[x]
print(new_array)

[41 43 78 45]


**Problem Statement: Create a Filter that will return only values higher than 34**

In [28]:
my_array = np.array([2,87,42,5,8,23,46,41,100,50,20,34,45,77,60])

# Create Empty list
filter_array = []

# go throgh each elements in array
for elements in my_array:
    # if the elements is higher than 34, set the values to True, otherwise False
    if elements >= 34:
        filter_array.append(True)
    else:
        filter_array.append(False)
        
new_array = my_array[filter_array]

# print(filter_array)
print(new_array)

[ 87  42  46  41 100  50  34  45  77  60]


In [30]:
my_array = np.array([2,87,42,5,8,23,46,41,100,50,20,34,45,77,60])

# Create Empty list
filter_array = []

# go throgh each elements in array
for elements in my_array:
    # if the elements is higher than 34, set the values to True, otherwise False
    if elements % 2 == 0:
        filter_array.append(True)
    else:
        filter_array.append(False)
        
new_array = my_array[filter_array]

# print(filter_array)
x = np.sort(new_array)
print(x)

[  2   8  20  34  42  46  50  60 100]


In [33]:
import numpy as np
my_array = np.array([2,87,42,5,8,23,46,41,100,50,20,34,45,77,60])

# Create Empty list
filter_array = []

# go throgh each elements in array
for elements in my_array:
    # if the elements is higher than 34, set the values to True, otherwise False
    if elements % 2 == 1:
        filter_array.append(True)
    else:
        filter_array.append(False)
        
new_array = my_array[filter_array]

# print(filter_array)
print(new_array)
# x = np.sort(new_array)
# print(x)

[87  5 23 41 45 77]


# Random Numbers in Numpy

In [6]:
from numpy import random

## Integer Numbers

In [38]:
x = random.randint(100)
print(x)

54


## Float Numbers

In [41]:
x = random.rand()
print(x)

0.6472672117569812


## Generate Random Array

In [9]:
x = random.randint(100, size =(10))
x

array([48, 66, 77, 14, 96, 18, 40, 41, 67, 44])

## Generate 2-D Arrays

In [48]:
x = random.randint(100, size =(4,5))
print(x)

[[39 81 81  3 89]
 [48 42 25 86 54]
 [77 56 11 45 49]
 [69 41 26 97 81]]


## Generate 3-D Arrays

In [51]:
x = random.randint(100, size =(2,2,4))
y = np.sort(x)
print(y)

[[[ 2 14 43 98]
  [16 30 35 56]]

 [[ 7 10 22 26]
  [21 47 60 67]]]


# Generate Floating Arrays:
    1. 1-D 
    2. 2-D
    3. 3-D

## 1-D arrays

In [11]:
x = random.rand(5)
print(x)

[0.57074336 0.22896762 0.95422612 0.37084031 0.37169642]


## 2-D Arrrays

In [12]:
x = random.rand(3,5)
print(x)

[[0.63691444 0.85334199 0.98396473 0.25716045 0.68666363]
 [0.15242616 0.61202598 0.25631921 0.718675   0.05605713]
 [0.51627498 0.0385318  0.37953233 0.60316431 0.19418629]]


## 3-D Arrays

In [16]:
x = random.rand(2,2,3)
print(x)

[[[0.13416455 0.29883206 0.46649222]
  [0.1419037  0.12892218 0.80523295]]

 [[0.81185899 0.95988936 0.57311968]
  [0.24797972 0.92435206 0.39729458]]]
