# Shape of Array

1. Shape of array is the number of elements in each dimension
2. Numpy array having one attributes called as [shape] 
3. shape returns a tuple with each index having number of corresponding elements

In [2]:
import numpy as np

In [4]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(my_array.shape)

(2, 5)


In [3]:
my_array = np.array([10,20,30,40,50,60,70,80], ndmin = 5)
print(my_array)
print("Shape of Array : ", my_array.shape)

[[[[[10 20 30 40 50 60 70 80]]]]]
Shape of Array :  (1, 1, 1, 1, 8)


In [7]:
my_array = np.array([[10,20,30,40],[50,60,70,80]], ndmin = 4)
print(my_array)
print("Shape of Array : ", my_array.shape)

[[[[10 20 30 40]
   [50 60 70 80]]]]
Shape of Array :  (1, 1, 2, 4)


## Reshaping Arrays

1. Reshaping means changing the shape of array
2. Shape of array is the number of elements in each dimension
3. By reshaping we can add or remove dimensions or change number of elemnents in each dimension
4. There are different ways to Reshaping array:
    1. 1-D to 2-D
    2. 1-D to 3-D

### 1. Reshape array from 1-D to 2-D

In [4]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(4,3)
print(new_array)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [5]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(6,2)
print(new_array)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]]


In [7]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(3,4)
print(new_array)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [8]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(2,6)
print(new_array)

[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


### 2. Reshape array from 1-D to 3-D

In [9]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(2,3,2)
print(new_array)

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]]


In [10]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(3,2,2)
print(new_array)

[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]


In [12]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(2,2,3)
print(new_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [13]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(1,6,2)
print(new_array)

[[[ 10  20]
  [ 30  40]
  [ 50  60]
  [ 70  80]
  [ 90 100]
  [110 120]]]


In [14]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(2,3)
print(new_array)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [15]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

print(my_array.reshape(6,2).base)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


### Unknown Dimesion:
    1. allowed to Unknown Dimensions
    2. that means you do not habe to spefify an exact number of dimension in the reshape method
    3. Pass -1 as the value, and calculates number of dimesions

In [24]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

new_array = my_array.reshape(1,3,-1)
print(new_array)

[[[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]


In [15]:
my_array = np.array([10,20,30,40,50,60,70,80])

new_array = my_array.reshape(2,2,-1)
print(new_array)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


### Flattring the arrray:
    1. Flattering the array means converting any multidimensional array into a 1-D Array
    2. we can use reshape(-1) 

In [19]:
import numpy as np

my_array = np.array([[10,20,30,40,50,60,70,80,90,100,110,120]])

new_array = my_array.reshape(-1)
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [13]:
my_array = np.array([[[ 10,20],[ 30, 40]],[[ 50, 60],[ 70, 80]],[[ 90, 100],[110, 120]]])

new_array = my_array.reshape(-1)
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


# Itrating Array:
    1. 1-D Array
    2. 2-D Array
    3. 3-D Array

## 1. 1-D Array

In [25]:
my_array = np.array([10,20,30,40,50,60,70,80])
print(my_array)

[10 20 30 40 50 60 70 80]


In [26]:
my_array = np.array([10,20,30,40,50,60,70,80])
my_array[0]

10

In [27]:
my_array = np.array([10,20,30,40,50,60,70,80])

for x in my_array:
    print(x)

10
20
30
40
50
60
70
80


## 2. 2-D Array

In [28]:
my_array = np.array([[ 10, 20, 30, 40],
 [ 50, 60, 70, 80],
 [ 90, 100, 110, 120]])

for x in my_array:
    print(x)

[10 20 30 40]
[50 60 70 80]
[ 90 100 110 120]


In [29]:
my_array = np.array([[ 10, 20, 30, 40],
 [ 50, 60, 70, 80],
 [ 90, 100, 110, 120]])

for x in my_array:
    for y in x:
        print(y)

10
20
30
40
50
60
70
80
90
100
110
120


## 3. Itrating 3-D Array

In [31]:
my_array = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])

for x in my_array:
    print(x)

[[10 20 30 40]
 [50 60 70 80]]
[[ 90 100 110 120]
 [130 140 150 160]]


In [32]:
my_array = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])

for x in my_array:
    for y in x:
        print(y)

[10 20 30 40]
[50 60 70 80]
[ 90 100 110 120]
[130 140 150 160]


In [33]:
my_array = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])

for x in my_array:
    for y in x:
        for z in y:
            print(z)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160


# Itrating array using nditer()

1. Function [nditer()] is a helping function that can be used from very basic to advanced itration
2. Function [nditer()] solves some basic issues which we face in itration

In [34]:
my_array = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])

for x in np.nditer(my_array):
    print(x)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160


In [50]:
my_array = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])

for x in np.nditer(my_array[:,0:2:1]):
    print(x)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160


# Itrating array using ndenumerate()

In [26]:
import numpy as np

a = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

for index,num in np.ndenumerate(a):
    print(index,num)

(0, 0, 0) 10
(0, 0, 1) 20
(0, 1, 0) 30
(0, 1, 1) 40
(1, 0, 0) 50
(1, 0, 1) 60
(1, 1, 0) 70
(1, 1, 1) 80


In [52]:
my_array = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])

for shyam, x in np.ndenumerate(my_array):
    print(shyam, x)

(0, 0, 0) 10
(0, 0, 1) 20
(0, 0, 2) 30
(0, 0, 3) 40
(0, 1, 0) 50
(0, 1, 1) 60
(0, 1, 2) 70
(0, 1, 3) 80
(1, 0, 0) 90
(1, 0, 1) 100
(1, 0, 2) 110
(1, 0, 3) 120
(1, 1, 0) 130
(1, 1, 1) 140
(1, 1, 2) 150
(1, 1, 3) 160


In [53]:
my_array = np.array([[ 10, 20, 30, 40],
 [ 50, 60, 70, 80],
 [ 90, 100, 110, 120]])

for idx, x in np.ndenumerate(my_array):
    print(idx, x)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(0, 3) 40
(1, 0) 50
(1, 1) 60
(1, 2) 70
(1, 3) 80
(2, 0) 90
(2, 1) 100
(2, 2) 110
(2, 3) 120


In [54]:
my_array = np.array([[ 10, 20, 30, 40],
 [ 50, 60, 70, 80],
 [ 90, 100, 110, 120]])

for x in np.ndenumerate(my_array):
    print(x)

((0, 0), 10)
((0, 1), 20)
((0, 2), 30)
((0, 3), 40)
((1, 0), 50)
((1, 1), 60)
((1, 2), 70)
((1, 3), 80)
((2, 0), 90)
((2, 1), 100)
((2, 2), 110)
((2, 3), 120)
