In [1]:
import numpy

In [3]:
my_array = numpy.array([1,2,3,4,5])
print(my_array)

[1 2 3 4 5]


In [4]:
import numpy as np

In [5]:
my_array = np.array([10,20,30,40,50])
print(my_array)

[10 20 30 40 50]


### Version

In [6]:
print(np.__version__)

1.20.1


# Creating Array [n-dimensional - ndarray]

1. Numpy is used to work with array. The array object is Numpy called as ndarray
2. We can create a Numpy ndarray object by using the array()

In [8]:
import numpy as np

my_array = np.array([10,20,30,40,50])
print(my_array)

print(type(my_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


## There are different types of ndarray:
    1. 0-D array
    2. 1-D array
    3. 2-D array
    4. 3-D array

### 1. 0-D arrays

In [9]:
import numpy as np

my_array = np.array(40)
print(my_array)

40


### 2. 1-D arrays:
    1. Array has 0-D arrays as its elements is called as 1-D array or Uni-Dimensional array
    2. The most common array

In [10]:
import numpy as np

my_array = np.array([10,20,30,40,50])
print(my_array)

[10 20 30 40 50]


### 3. 2-D arrays
    1. An array that has 1-D arrays as its elements is called as 2-D array
    2. used to represent matrix or 2nd order tensors

In [12]:
import numpy as np

my_array = np.array([[10,20,30,40],[50,60,70,80]])
print(my_array)

[[10 20 30 40]
 [50 60 70 80]]


### 4. 3-D arrays
    1. An array that has 2-D array (matrices) as its elements is called as 3-D array
    2. used to represent a 3rd order tensor

In [13]:
import numpy as np

my_array = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(my_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


# Number of Dimensions

In [14]:
import numpy as np

my_array = np.array(48)
my_array1 = np.array([10,20,30,40,50])
my_array2 = np.array([[10,20,30,40],[50,0,70,80]])
my_array3 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

print(my_array.ndim)
print(my_array1.ndim)
print(my_array2.ndim)
print(my_array3.ndim)

0
1
2
3


## Higher Dimensional Arrays

In [21]:
my_array = np.array([10,20,30,40,50,60,70,80,90],ndmin = 7)
print(my_array)
print("Number of Dimension: ", my_array.ndim)

[[[[[[[10 20 30 40 50 60 70 80 90]]]]]]]
Number of Dimension:  7


# 2. Access Arrays Elements

1. Numpy Array indexing is the same as accessing an array elements
2. you can access an array elements by reffering index number
3. Numpy Array indexing start with 0, that means first elements has index 0, second elements is ...
4. There are differnt types of Dimension of Array accssing using indexing:
    1. 0-D array
    2. 1-D array
    3. 2-D array
    4. 3-D array
5. There are two types indexing to accessing arrays elements:
    1. Positive Indexing
    2. Negative Indexing

## 1. Positive Indexing

### 1. 0-D arrays

In [24]:
my_array = np.array(48)

print(my_array)

48


### 2. 1-D Arrays

In [27]:
my_array1 = np.array([10,20,30,40,50])

my_array1[4]

50

In [29]:
my_array1[0] + my_array1[4]

60

### 3. 2-D arrays

In [2]:
import numpy as np
my_array2 = np.array([[10,20,30,40],[50,60,70,80]])

my_array2[0,3]

40

In [31]:
my_array2 = np.array([[10,20,30,40],[50,60,70,80]])

print(my_array2[1,3])

80


In [33]:
print(my_array2[0,])

[10 20 30 40]


In [34]:
print(my_array2[1,])

[50 60 70 80]


In [36]:
my_array2 = np.array([[10,20,30,40,50,60]])

print(my_array2[0,])

[10 20 30 40 50 60]


In [40]:
my_array2 = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])

print(my_array2[1,])

[ 70  80  90 100 110 120]


### 4. Access 3-D Arrays

In [41]:
my_array3 = np.array([ [[10,20,30],[40,50,60]] , [[70,80,90],[100,110,120]] ])

print(my_array3[0,1,2])

60


In [42]:
my_array3 = np.array([ [[10,20,30],[40,50,60]], [[70,80,90],[100,110,120]] ])

print(my_array3[1,0,2])

90


In [43]:
my_array3 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

print(my_array3[1,1,0])

100
