# Joining Numpy Arrays

1. Joining means putting contents of two or more arrays in a single row
2. In SQL, we can join table based on key, whereas in Numpy we join using axes
3. We pass sequence of arrays we want to join the array concatenate()
4. all the input arrays must have same number of dimensions.

In [8]:
import numpy as np

In [3]:
my_array1 = np.array([10,20,30,40,50])
my_array2 = np.array([60,70,80,90,100])

new_array = np.concatenate((my_array1, my_array2))
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [5]:
my_array1 = np.array([[1,2],[3,4]])
my_array2 = np.array([[8,9],[7,6]])

new_array = np.concatenate((my_array1, my_array2), axis = 0)

print(new_array)

[[1 2]
 [3 4]
 [8 9]
 [7 6]]


In [4]:
my_array1 = np.array([10,20,30,40,50,60])
my_array2 = np.array([[70,80,90,91,92,93]])

new_array = np.concatenate((my_array1, my_array2), axis = 0)

print(new_array)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

# Joining Arrays Using Stack Functions

1. Stacking is same as concatenation, the only difference is that stacking is done along with axis
2. We can concatenate two 1-D arrays along with the second which result in putting them one over the other
3. joining array must be in same shape

In [7]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = np.stack((my_array1, my_array2), axis=1)
print(new_array)

[[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [5]:
import numpy as np
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = np.stack((my_array1, my_array2), axis=0)
print(new_array)

[[10 20 30 40]
 [50 60 70 80]]


## Stacking Along Rows
    Note:- NO need to have equal number of element in both the array.

In [3]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80,90,100])

new_array = np.hstack((my_array1, my_array2))
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100]


## Stacking Along Columns    
    Note:- Need to have equal number of element in both the array.

In [7]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = np.vstack((my_array1, my_array2))
print(new_array)

[[10 20 30 40]
 [50 60 70 80]]


## Stacking Along Height (depth)

In [11]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = np.dstack((my_array1, my_array2))
print(new_array)

[[[10 50]
  [20 60]
  [30 70]
  [40 80]]]


In [12]:
my_array1 = np.array([[10,20,30],[40,50,60]])
my_array2 = np.array([[70,80,90],[91,92,93]])

new_array = np.dstack((my_array1, my_array2))

print(new_array)

[[[10 70]
  [20 80]
  [30 90]]

 [[40 91]
  [50 92]
  [60 93]]]


In [14]:
# help(np.dstack)

In [16]:
# help(np.column_stack)

In [11]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array1 = np.column_stack((my_array1, my_array2))
print(new_array1)

[[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [19]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = np.column_stack((my_array1, my_array2))
print(new_array)

[[10 50]
 [20 60]
 [30 70]
 [40 80]]


# Splitting the Arrays

1. Splitting is reverse operation of Joining
2. Joining means multiple arrays into one and Splitting breaks one array into multiple
3. using array_split() for splitting arrays, we pass it the array and number of splits

In [6]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1, 3)
print(new_array)

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]


In [18]:
my_array1 = np.array([[10, 50],[20, 60],[30, 70],[40, 80]])

new_array = np.array_split(my_array1, 3)
print(new_array)

[array([[10, 50],
       [20, 60]]), array([[30, 70]]), array([[40, 80]])]


In [21]:
print(new_array[0])

print(new_array[1])
print(new_array[2])
print(new_array[0][1])

[[10 50]
 [20 60]]
[[30 70]]
[[40 80]]
[20 60]


In [22]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1, 4)
print(new_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80]), array([ 90, 100])]


In [25]:
# help(np.split)

In [27]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90])

new_array = np.array_split(my_array1, 4)
print(new_array)

[array([10, 20, 30]), array([40, 50]), array([60, 70]), array([80, 90])]


In [28]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1, 5)
print(new_array)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100])]


In [29]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1, 6)
print(new_array)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([90]), array([100])]


In [31]:
print(new_array[0])
print(new_array[1])
print(new_array[2])
print(new_array[3])
print(new_array[4])
print(new_array[5])

[10 20]
[30 40]
[50 60]
[70 80]
[90]
[100]


In [32]:
print(new_array[1][1])

40


In [34]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1, 2)
print(new_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [36]:
print(new_array[1][0:3])

[60 70 80]
