In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('DT.csv' ,encoding = 'unicode_escape')

In [3]:
df.head()

Age  Income Student Credit_rating Class: buys_computer
0   <=30    High      No          Fair                   No
1   <=30    High      No     Excellent                   No
2  31-40    High      No          Fair                  Yes
3    >40  Medium      No          Fair                  Yes
4    >40     Low     yes          Fair                  Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Age                   14 non-null     object
 1   Income                14 non-null     object
 2   Student               14 non-null     object
 3   Credit_rating         14 non-null     object
 4   Class: buys_computer  14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes


In [5]:
df['Age'].unique()

array(['<=30', '31-40', '>40'], dtype=object)

In [6]:
age = pd.get_dummies(df['Age'],drop_first=True)
age.head()

<=30  >40
0     1    0
1     1    0
2     0    0
3     0    1
4     0    1

In [7]:
income = pd.get_dummies(df['Income'],drop_first=True)
income.head()

Low  Medium
0    0       0
1    0       0
2    0       0
3    0       1
4    1       0

In [8]:
student = pd.get_dummies(df['Student'],drop_first=True)
std = student.drop('no',axis=1)

In [9]:
CreditRating = pd.get_dummies(df['Credit_rating'],drop_first=True)
CreditRating.head()

Fair
0     1
1     0
2     1
3     1
4     1

In [10]:
Class_buy = pd.get_dummies(df['Class: buys_computer'],drop_first=True)
Class_buy.head()

Yes
0    0
1    0
2    1
3    1
4    1

In [11]:
df1 = pd.concat([age,income,std,CreditRating,Class_buy],axis=1)

In [12]:
df1.head()

<=30  >40  Low  Medium  yes  Fair  Yes
0     1    0    0       0    0     1    0
1     1    0    0       0    0     0    0
2     0    0    0       0    0     1    1
3     0    1    0       1    0     1    1
4     0    1    1       0    1     1    1

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   <=30    14 non-null     uint8
 1   >40     14 non-null     uint8
 2   Low     14 non-null     uint8
 3   Medium  14 non-null     uint8
 4   yes     14 non-null     uint8
 5   Fair    14 non-null     uint8
 6   Yes     14 non-null     uint8
dtypes: uint8(7)
memory usage: 226.0 bytes


In [14]:
x = df1.drop('Yes',axis =1)
y = df1['Yes']

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=1)

# Random Forest 

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
RFC_model = RandomForestClassifier(n_estimators= 100, criterion='entropy')
model = RFC_model.fit(x_train, y_train)

In [18]:
prediction = model.predict(x_test)
print(prediction)

[1 0 1]


In [19]:
print(y_test)

3    1
7    0
6    1
Name: Yes, dtype: uint8


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [21]:
print(confusion_matrix(y_test, prediction))

[[1 0]
 [0 2]]


In [22]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [23]:
accuracy_score(y_test, prediction)

1.0

# Decision Tree

In [40]:
x_train.shape,x_test.shape

((11, 6), (3, 6))

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
model = DecisionTreeClassifier(criterion='entropy', max_depth=6)

In [26]:
decision_model = model.fit(x_train, y_train)

In [27]:
model = DecisionTreeClassifier(criterion='gini', max_depth=6)

In [28]:
decision_model = model.fit(x_train, y_train)

In [29]:
prediction = decision_model.predict(x_test)
print(prediction)

[1 0 0]


In [30]:
print(y_test)

3    1
7    0
6    1
Name: Yes, dtype: uint8


In [37]:
prediction_train = decision_model.predict(x_train)
print(prediction_train)

[1 1 1 0 1 0 0 1 1 1 0]


In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [32]:
print(confusion_matrix(y_test, prediction))

[[1 0]
 [1 1]]


In [33]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3



In [38]:
train_accuracy = accuracy_score(y_train, prediction_train)
print(train_accuracy)

1.0


In [35]:
test_accuracy = accuracy_score(y_test, prediction)
print(test_accuracy)

0.6666666666666666
