# Checking the data type of Array

## Data Types in Numpy:
1. Numpy has some extra data types, and refers to the only single character like, i for integer
2. i - integer
3. b - boolean
4. u - unsigned integer
5. f - float
6. c - complex float
7. M - timedelta
8. O - object
9. S - String
10. U - Unicode String
11. V - Fixed chunks of memory for other types (void)

In [32]:
import numpy as arr

In [33]:
my_array = arr.array([1,2,3,4])
my_array.dtype



dtype('int32')

In [3]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
arr.dtype

dtype('<U6')

## Creating array with Defined Data Types

In [4]:
import numpy as np
my_array = np.array([10,20,30,40],dtype ='S')
print(my_array)
print(my_array.dtype)
print(my_array.dtype=='bool')

[b'10' b'20' b'30' b'40']
|S2
False


In [5]:
import numpy as np
my_array = np.array([10,20,30,40],dtype='i')
print(my_array)
print(my_array.dtype)

[10 20 30 40]
int32


In [6]:
import numpy as np
my_array = np.array([10,20,30,40],dtype='i8')
print(my_array)
print(my_array.dtype)

[10 20 30 40]
int64


## What if A Value can not be Converted?

In [7]:
import numpy as np
my_array = np.array(['a','12.12','10.23','10','20','30','40'],dtype='i')
print(my_array)
print(my_array.dtype)

ValueError: invalid literal for int() with base 10: 'a'

## Converting Data Type of Existing Arrays

1. The Best way to change the data type of an existing array, is to make a copy of array with the astype() method.
2. The astype() function creates a copy of array, and it allows you to spefify the data type as parameter
3. Data type can be specified using string like 'f' for float, 'i' for integer etc.
4. Data type directly pass like float for decimal type of data,int for integer type of data

In [21]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype('i')
print(new_array)
print(new_array.dtype)

[10.23 20.34 30.56 24.89]
float64
[10 20 30 24]
int32


In [10]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype(int)
print(new_array)
print(new_array.dtype)
 

[10.23 20.34 30.56 24.89]
float64
[10 20 30 24]
int32


In [11]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype(bool)
print(new_array)
print(new_array.dtype)

[10.23 20.34 30.56 24.89]
float64
[ True  True  True  True]
bool


In [12]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype('U')
print(new_array)
print(new_array.dtype)

[10.23 20.34 30.56 24.89]
float64
['10.23' '20.34' '30.56' '24.89']
<U32


In [13]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype('V')
print(new_array)
print(new_array.dtype)

[10.23 20.34 30.56 24.89]
float64
[b'\xF6\x28\x5C\x8F\xC2\x75\x24\x40' b'\xD7\xA3\x70\x3D\x0A\x57\x34\x40'
 b'\x8F\xC2\xF5\x28\x5C\x8F\x3E\x40' b'\xA4\x70\x3D\x0A\xD7\xE3\x38\x40']
|V8


In [14]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype('c')
print(new_array)
print(new_array.dtype)

[10.23 20.34 30.56 24.89]
float64
[b'1' b'2' b'3' b'2']
|S1


In [15]:
import numpy as np

my_array =np.array([10.23,20.34,30.56,24.89])
print(my_array)
print(my_array.dtype)

new_array = my_array.astype('m')
print(new_array)
print(new_array.dtype)

[10.23 20.34 30.56 24.89]
float64
[10 20 30 24]
timedelta64


# The Difference Between Copy and View

1. The main differnce between a copy and a view of an array is that the copy is a new array
2. View is just a view of the original array

### 1. Copy

1. The copy owns the data and any changes made to the copy will not affect original array
2. any changes made to the original array that does not affect to the copy array

In [16]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90])

# To copy original array
x = my_array.copy()

# To add new elements in orignal array
my_array[0] = 100 


print(my_array)
print(x)

[100  20  30  40  50  60  70  80  90]
[10 20 30 40 50 60 70 80 90]


In [17]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90])

# To copy original array
x = my_array.copy()

# To add new elements in copy array
x[0] = 100 


print(my_array)
print(x)

[10 20 30 40 50 60 70 80 90]
[100  20  30  40  50  60  70  80  90]


### 2. View:
    1. The View does not owns the data and any changes made to the view will affected to the original array
    2. any changes made in the original array will affect the view

In [18]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90])
print("Original Array: ", my_array)

# To copy original array
x = my_array.view()

# To add new elements in orignal array
my_array[0] = 100 


print("After changes made in original array (Original): ",my_array)
print("Afer changes made in original array (View): ",x)

Original Array:  [10 20 30 40 50 60 70 80 90]
After changes made in original array (Original):  [100  20  30  40  50  60  70  80  90]
Afer changes made in original array (View):  [100  20  30  40  50  60  70  80  90]


In [19]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90])
print("Original Array: ", my_array)

# To copy original array
x = my_array.view()

# To add new elements in orignal array
x[0] = 100 


print("After changes made in View array (Original): ",my_array)
print("Afer changes made in View array (View): ",x)

Original Array:  [10 20 30 40 50 60 70 80 90]
After changes made in View array (Original):  [100  20  30  40  50  60  70  80  90]
Afer changes made in View array (View):  [100  20  30  40  50  60  70  80  90]


### Check if array owns the data or not?

In [20]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,80,90])


x = my_array.copy()
y = my_array.view()

print(x.base)
print(y.base)

None
[10 20 30 40 50 60 70 80 90]
