# Splitting Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_array = np.array([10,20,30,40,50,60,70,80,90])

new_array = np.array_split(my_array, 3)
print(new_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]


In [3]:
my_array = np.array([10,20,30,40,50,60,70,80,90])

new_array = np.array_split(my_array, 4)
print(new_array)

[array([10, 20, 30]), array([40, 50]), array([60, 70]), array([80, 90])]


In [4]:
print(new_array[1])

[40 50]


In [5]:
print(new_array[3])

[80 90]


In [7]:
print(new_array[3][-1])

90


In [8]:
print(new_array[2][-1])

70


In [9]:
print(new_array[0][0:2])

[10 20]


## Splitting 2-D Arrays

In [14]:
my_array = np.array([[10,20,30,40],[50,60,70,80],[100,110,120,130],[140,150,160,170]])

new_array = np.array_split(my_array, 3)
print(new_array)

[array([[10, 20, 30, 40],
       [50, 60, 70, 80]]), array([[100, 110, 120, 130]]), array([[140, 150, 160, 170]])]


In [16]:
my_array = np.array([[10,20,30,40],[50,60,70,80],[100,110,120,130],[140,150,160,170]])

new_array = np.array_split(my_array, 4)
print(new_array)

[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([[100, 110, 120, 130]]), array([[140, 150, 160, 170]])]


In [21]:
print(new_array[0][0][1])

20


In [24]:
print(new_array[2][0][2])

120


In [26]:
my_array = np.array([[10,20,30,40],[50,60,70,80],[100,110,120,130],[140,150,160,170]])

new_array = np.array_split(my_array, 2, axis=1)
print(new_array)

[array([[ 10,  20],
       [ 50,  60],
       [100, 110],
       [140, 150]]), array([[ 30,  40],
       [ 70,  80],
       [120, 130],
       [160, 170]])]


In [30]:
my_array = np.array([[10,20,30,40],[50,60,70,80],[100,110,120,130],[140,150,160,170]])

new_array = np.hsplit(my_array, 2)
print(new_array)

[array([[ 10,  20],
       [ 50,  60],
       [100, 110],
       [140, 150]]), array([[ 30,  40],
       [ 70,  80],
       [120, 130],
       [160, 170]])]


In [31]:
my_array = np.array([[10,20,30,40,23,45],[50,60,70,80,34,56],[100,110,120,130,35,67],[140,150,160,170,78,79]])

new_array = np.hsplit(my_array, 3)
print(new_array)

[array([[ 10,  20],
       [ 50,  60],
       [100, 110],
       [140, 150]]), array([[ 30,  40],
       [ 70,  80],
       [120, 130],
       [160, 170]]), array([[23, 45],
       [34, 56],
       [35, 67],
       [78, 79]])]


In [ ]:
my_array = np.array([[10,20,30,40,23,45],[50,60,70,80,34,56],[100,110,120,130,35,67],[140,150,160,170,78,79]])

new_array = np.hsplit(my_array, 4)
print(new_array)

In [33]:
my_array = np.array([[10,20,30,40,23,45],[50,60,70,80,34,56],[100,110,120,130,35,67],[140,150,160,170,78,79]])

new_array = np.hsplit(my_array, 6)
print(new_array)

[array([[ 10],
       [ 50],
       [100],
       [140]]), array([[ 20],
       [ 60],
       [110],
       [150]]), array([[ 30],
       [ 70],
       [120],
       [160]]), array([[ 40],
       [ 80],
       [130],
       [170]]), array([[23],
       [34],
       [35],
       [78]]), array([[45],
       [56],
       [67],
       [79]])]


# Searching Arrays

1. Search array for certain value and return the indexes that get match
2. To search an array use, where() method

In [34]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70])

x  = np.where(my_array == 50)
print(x)

(array([4], dtype=int64),)


In [35]:
import numpy as np

my_array = np.array([10,20,30,40,50,60,70,40,60,40])

x  = np.where(my_array == 40)
print(x)

(array([3, 7, 9], dtype=int64),)


In [37]:
import numpy as np

my_array = np.array([1,2,3,4,5,6,7])

x  = np.where(my_array%2 == 0)
print(x)

(array([1, 3, 5], dtype=int64),)


In [38]:
import numpy as np

my_array = np.array([1,2,3,4,5,6,7])

x  = np.where(my_array%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Binary Search 

![](https://www.geeksforgeeks.org/wp-content/uploads/Binary-Search.png)

In [39]:
import numpy as np

my_array = np.array([1,2,3,4,5,6,7])

x = np.searchsorted(my_array,7)
print(x)

6


In [45]:
import numpy as np

# my_array = np.array([2,5,8,12,16,23,38,56,72,91])
my_array= np.array([91,72,2,16,56,12,8,38,23,8])

x = np.searchsorted(my_array,8)
print(x)

3
